/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.gui.usergui;

import org.example.dao.UserDAO;
import org.example.model.ChargeOrder;
import org.example.model.FoodOrder;
import org.example.model.User;

/**
 *
 * @author khoa
 */
public class OrderItem extends javax.swing.JPanel {

    /**
     * Creates new form OrderItem
     */
    public OrderItem(Object o) {
        initComponents();
        try {
            if (o instanceof FoodOrder) {
                FoodOrder ord = (FoodOrder) o;
                lblName.setText(ord.getOrderProduct().getProduct_name());
                lblUsername.setText(new UserDAO().getUsername(ord.getUserId()));
                lblTime.setText(ord.getDateTime().toString());
                lblAmount.setText(String.valueOf(ord.getOrderAmount()));
                lblTotal.setText(String.valueOf(ord.getTotalMoney()));
                if (ord.getIsPaid()) {
                    lblStatus.setText("Đã thanh toán");
                }
                else {
                    lblStatus.setText("Chưa thanh toán");
                }
            }
            if (o instanceof ChargeOrder) {
                ChargeOrder ord = (ChargeOrder) o;
                lblName.setText("Nạp tiền");
                lblUsername.setText(new UserDAO().getUsername(ord.getUserId()));
                lblTime.setText(ord.getDateTime().toString());
                lblAmount.setText(String.valueOf(ord.getTotalMoney()));
                lblTotal.setText(String.valueOf(ord.getTotalMoney()));
                if (ord.getIsPaid()) {
                    lblStatus.setText("Đã thanh toán");
                }
                else {
                    lblStatus.setText("Chưa thanh toán");
                }
            }
        }
        catch (Exception e) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setText("Name");

        lblUsername.setText("jLabel2");

        lblTime.setText("jLabel3");

        lblAmount.setText("jLabel4");

        lblTotal.setText("jLabel5");

        lblStatus.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblUsername)
                    .addComponent(lblTime)
                    .addComponent(lblAmount)
                    .addComponent(lblTotal)
                    .addComponent(lblStatus))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
