/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.gui.admingui;

import javax.swing.JOptionPane;
import org.example.dao.ProductDAO;
import org.example.model.Product;

/**
 *
 * @author khoa
 */
public class ServiceAdjustGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServiceAdjustGUI.class.getName());
    private Product pd;
    /**
     * Creates new form ServiceAdjustGUI
     */
    public ServiceAdjustGUI(Product pd) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        pack();
        this.pd = pd;
        loadProduct();
        if (pd.getProduct_id() == 1) {
            txtCost.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtImg = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnDone1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtImg.setText("images/");

        jLabel1.setText("Tên SP");

        jLabel2.setText("Giá ");

        jLabel3.setText("Đường dẫn ảnh");

        jLabel5.setText("Sửa thông tin sản phẩm");

        btnDone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDone.setText("Xong");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnDone1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDone1.setText("Hủy");
        btnDone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDone1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnDone1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(231, 231, 231))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDone1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDone1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnDone1ActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        String name = txtName.getText().trim();
        String cost = txtCost.getText().trim();
        String img = txtImg.getText().trim();

        // KIỂM TRA DỮ LIỆU
        if (pd.getProduct_id() != 1) {

            if (name.isEmpty() || cost.isEmpty() || img.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin!","Thiếu dữ liệu",JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                Double.parseDouble(cost);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Giá tiền phải là số!","Lỗi dữ liệu",JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- Gọi DAO để cập nhật ---
            ProductDAO dao = new ProductDAO();
            boolean success = dao.adjustProduct(name, cost, img,pd.getProduct_id());

            if (success) {
                JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);


                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại! Vui lòng kiểm tra lại.","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
        else {

            if (name.isEmpty() || img.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin!","Thiếu dữ liệu",JOptionPane.WARNING_MESSAGE);
                return;
            }

            // --- Gọi DAO để cập nhật ---
            ProductDAO dao = new ProductDAO();
            boolean success = dao.adjustProduct(name, null, img,pd.getProduct_id());

            if (success) {
                JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);


                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại! Vui lòng kiểm tra lại.","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnDoneActionPerformed

    public void loadProduct() {
        txtName.setText(pd.getProduct_name());
        txtCost.setText(pd.getProduct_cost());
        txtImg.setText(pd.getProduct_image());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnDone1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
