/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.gui.admingui;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListSelectionModel;
import static org.example.dao.OrderDAO.getAllOrders;
import org.example.model.ChargeOrder;
import org.example.model.FoodOrder;

/**
 *
 * @author khoa
 */
public class StatisticGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatisticGUI.class.getName());
    ArrayList<Object> orders = getAllOrders();
    AdminMainGUI a;
    /**
     * Creates new form StatisticGUI
     */
    public StatisticGUI(AdminMainGUI a) {
        initComponents();
        this.a = a;
        pack();
        setLocationRelativeTo(null);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGet = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnGet.setText("Lấy dữ liệu");
        btnGet.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                btnGetAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập tên file bạn muốn lưu dữ liệu");

        jLabel2.setText("Bạn muốn lấy dữ liệu theo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tháng", "Năm" }));

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 131, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnGet, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGet)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnGetAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_btnGetAncestorMoved
        

    }//GEN-LAST:event_btnGetAncestorMoved

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        switch(jComboBox1.getSelectedItem().toString().trim()) {
            case ("Ngày"):
            {
                try {
                    thongKeTheoNgay(orders,jTextField1.getText());
                    System.out.println("hello");
                } catch (IOException ex) {
                    System.getLogger(StatisticGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                break;
                
            }
            case ("Tháng"):
            {
                try {
                    thongKeTheoThang(orders,jTextField1.getText());
                } catch (IOException ex) {
                    System.getLogger(StatisticGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                break;
            }

        
            case ("Năm"):
            {
                try {
                    thongKeTheoNam(orders,jTextField1.getText());
                } catch (IOException ex) {
                    System.getLogger(StatisticGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                break;
            }

        }
    }//GEN-LAST:event_btnGetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        a.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
        a.setVisible(true);
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    
    //------------------CÁC HÀM PHÂN TÍCH SỐ LIỆU VÀ THỐNG KÊ------------------------//
    private static long getBill(Object o) {
        if (o instanceof ChargeOrder co) {
            return co.getTotalMoney();
        }
        if (o instanceof FoodOrder fo) {
            return fo.getTotalMoney();
        }
        return 0;
    }

    private static LocalDate getDate(Object o) {
        if (o instanceof ChargeOrder co) {
            return co.getOrderDate();
        }
        if (o instanceof FoodOrder fo) {
            return fo.getOrderDate();
        }
        return null;
    }

    private static boolean isPaid(Object o) {
        if (o instanceof ChargeOrder co) {
            return co.getIsPaid();
        }
        if (o instanceof FoodOrder fo) {
            return fo.getIsPaid();
        }
        return false;
    }

    private static int getOrderType(Object o) {
        if (o instanceof ChargeOrder) {
            return 1;
        }
        if (o instanceof FoodOrder fo) {
            return fo.getOrderProduct().getProduct_id();
        }
        return -1;
    }

    public static void thongKeTheoNgay(ArrayList<Object> orders, String filename) throws FileNotFoundException, IOException {
        BufferedWriter bw = new BufferedWriter(new FileWriter(filename,true));


        class Stats {

            int totalOrders = 0;
            int paidOrders = 0;
            int unpaidOrders = 0;
            long totalRevenue = 0;
            long chargeRevenue = 0;                       // order_type == 1
            Map<Integer, Long> productRevenue = new HashMap<>(); // key = product_id
        }

        Map<LocalDate, Stats> map = new HashMap<>();

        for (Object o : orders) {
            LocalDate d = getDate(o);
            if (d == null) {
                continue;
            }

            Stats s = map.getOrDefault(d, new Stats());
            s.totalOrders++;

            // trạng thái thanh toán
            if (isPaid(o)) {
                s.paidOrders++;
            } else {
                s.unpaidOrders++;
            }

            long bill = getBill(o);
            s.totalRevenue += bill;

            int type = getOrderType(o);

            if (type == 1) {
                s.chargeRevenue += bill;
            } else {
                s.productRevenue.put(type,
                        s.productRevenue.getOrDefault(type, 0L) + bill);
            }

            map.put(d, s);
        }

        // IN RA
        for (LocalDate d : map.keySet()) {
            Stats s = map.get(d);
            StringBuilder text = new StringBuilder();

            text.append("===== NGÀY ").append(d).append(" =====\n");
            text.append("Tổng số đơn: ").append(s.totalOrders).append("\n");
            text.append("Đơn đã thanh toán: ").append(s.paidOrders).append("\n");
            text.append("Đơn chưa thanh toán: ").append(s.unpaidOrders).append("\n");
            text.append("Tổng doanh thu: ").append(s.totalRevenue).append("\n");
            text.append("Doanh thu nạp tiền (order_type=1): ").append(s.chargeRevenue).append("\n");

            text.append("Doanh thu từng loại sản phẩm:\n");
            for (int pid : s.productRevenue.keySet()) {
                text.append("  Product ID ").append(pid)
                        .append(": ").append(s.productRevenue.get(pid))
                        .append("\n");
            }

            text.append("--------------------------------------\n");
            bw.write(text.toString());
            
        }
        bw.close();
    }

    public static void thongKeTheoThang(ArrayList<Object> orders,String filename) throws IOException {
        BufferedWriter bw = new BufferedWriter(new FileWriter(filename,true));
        class Stats {

            int totalOrders = 0;
            int paidOrders = 0;
            int unpaidOrders = 0;
            long totalRevenue = 0;

            long chargeRevenue = 0;
            Map<Integer, Long> productRevenue = new HashMap<>();
        }

        Map<String, Stats> map = new HashMap<>();

        for (Object o : orders) {

            LocalDate d = getDate(o);
            if (d == null) {
                continue;
            }

            String key = d.getMonthValue() + "-" + d.getYear();

            Stats s = map.getOrDefault(key, new Stats());
            //THEM 1 VAO TONG ORDER
            s.totalOrders++;
            //TRA / CHUA TRA
            if (isPaid(o)) {
                s.paidOrders++;
            } else {
                s.unpaidOrders++;
            }
            //THEEM VAO TONG DOANH THU
            long bill = getBill(o);
            s.totalRevenue += bill;
            
            int type = getOrderType(o);
            if (type == 1) {
                s.chargeRevenue += bill;
            } else {
                s.productRevenue.put(type, s.productRevenue.getOrDefault(type, 0L) + bill);
            }

            map.put(key, s);
        }

        // IN RA
        for (String key : map.keySet()) {
            Stats s = map.get(key);
            StringBuilder text = new StringBuilder();
            text.append("===== THÁNG ").append(key).append(" =====\n");
            text.append("Tổng số đơn: ").append(s.totalOrders).append("\n");
            text.append("Đơn đã thanh toán: ").append(s.paidOrders).append("\n");
            text.append("Đơn chưa thanh toán: ").append(s.unpaidOrders).append("\n");
            text.append("Tổng doanh thu: ").append(s.totalRevenue).append("\n");
            text.append("Doanh thu nạp tiền (order_type=1): ").append(s.chargeRevenue).append("\n");

            text.append("Doanh thu theo sản phẩm:\n");
            for (int pid : s.productRevenue.keySet()) {
                text.append("  Product ID ").append(pid).append(": ").append(s.productRevenue.get(pid)).append("\n");
            }

            text.append("--------------------------------------\n");
            bw.write(text.toString());
           
        }
        bw.close();
    }

    public static void thongKeTheoNam(ArrayList<Object> orders,String filename) throws IOException {
        BufferedWriter bw = new BufferedWriter(new FileWriter(filename,true));

        class Stats {

            int totalOrders = 0;
            int paidOrders = 0;
            int unpaidOrders = 0;
            long totalRevenue = 0;

            long chargeRevenue = 0;
            Map<Integer, Long> productRevenue = new HashMap<>();
        }

        Map<Integer, Stats> map = new HashMap<>();

        for (Object o : orders) {
            LocalDate d = getDate(o);
            if (d == null) {
                continue;
            }

            int year = d.getYear();

            Stats s = map.getOrDefault(year, new Stats());
            s.totalOrders++;

            if (isPaid(o)) {
                s.paidOrders++;
            } else {
                s.unpaidOrders++;
            }

            long bill = getBill(o);
            s.totalRevenue += bill;

            int type = getOrderType(o);
            if (type == 1) {
                s.chargeRevenue += bill;
            } else {
                s.productRevenue.put(type, s.productRevenue.getOrDefault(type, 0L) + bill);
            }

            map.put(year, s);
        }

        // IN RA
        for (int year : map.keySet()) {
            Stats s = map.get(year);
            StringBuilder text = new StringBuilder();
            text.append("===== NĂM ").append(year).append(" =====").append("\n");
            text.append("Tổng số đơn: ").append(s.totalOrders).append("\n");
            text.append("Đơn đã thanh toán: ").append(s.paidOrders).append("\n");
            text.append("Đơn chưa thanh toán: ").append(s.unpaidOrders).append("\n");
            text.append("Tổng doanh thu: ").append(s.totalRevenue).append("\n");
            text.append("Doanh thu nạp tiền (order_type=1): ").append(s.chargeRevenue).append("\n");

            text.append("Doanh thu theo sản phẩm:\n");
            for (int pid : s.productRevenue.keySet()) {
                text.append("  Product ID ").append(pid).append(": ").append(s.productRevenue.get(pid)).append("\n");
            }

            text.append("--------------------------------------\n");
            bw.write(text.toString());
            
        }
        bw.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGet;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
